import turtle as tl


fond = tl.Turtle()
fen = tl.Screen()
fen.setup(width=800, height=800)
fond.pencolor('lime')
fen.delay(0)
fond.ht()
fond.fillcolor('lime')
fond.setpos(-325, -325)
fond.begin_fill()
fond.forward(650)
fond.left(90)
fond.forward(650)
fond.left(90)
fond.forward(650)
fond.end_fill()
car = tl.Turtle()
car.pencolor('red')
car.ht()
car.fillcolor('yellow')
for x in range(9):
    for i in range(9):
        car.penup()
        car.setpos(-325+((i*60)+(i+1)*11), -325+((x*60)+(x+1)*11))
        car.pendown()
        car.begin_fill()
        car.forward(60)
        car.left(90)
        car.forward(60)
        car.left(90)
        car.forward(60)
        car.left(90)
        car.forward(60)
        car.left(90)
        car.end_fill()

tl.done()